services:
  - type: web
    name: OpenVoice-Server
    runtime: python
    env: python
    buildCommand: |
      pyenv global 3.9.0
      pip install -r requirements.txt
    startCommand: uvicorn openvoice.openvoice_server:app --host 0.0.0.0 --port 8000
