services:
  - type: web
    name: OpenVoice-Server
    runtime: python
    env: python
    buildCommand:
      ./render-build.sh
    startCommand: uvicorn openvoice.openvoice_server:app --host 0.0.0.0 --port $PORT

